updated unchanged files test

diff --git a/.github/workflows/test_changed_files.yaml b/.github/workflows/test_changed_files.yaml
--- a/.github/workflows/test_changed_files.yaml
+++ b/.github/workflows/test_changed_files.yaml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   test-changed-file:
-    name: Check that changed-files action detects changed files
+    name: Check that changed-files action detects changed files in the current PR
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -18,6 +18,34 @@ jobs:
       - name: Get changed files
         id: changed-files
         uses: ./changed-files
+
+      - name: Check changed files output
+        run: |
+          changed_files="${{ steps.changed-files.outputs.changed-files }}"
+          expected_file="changed-files/action.yml"
+
+          if echo $changed_files | grep -F -q -x "$expected_file"; then
+            echo "$expected_file found in changed files"
+          else
+            echo "$expected_file not found in changed files"
+            exit 1
+          fi
+
+  test-known-refs:
+    name: Check that changed-files action works with custom refs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Get changed files
+        id: changed-files
+        uses: ./changed-files
+        with:
+          base-ref: a7fc56f262863f374b44aa020e163c013d3c75ad
+          head-ref: 20063fbd0a3dde28a87d0a8767a4f16c7a5c9c6e
 
       - name: Check changed files output
         run: |
@@ -43,10 +71,14 @@ jobs:
       - name: Get changed files
         id: changed-files
         uses: ./changed-files
+        with:
+          base-ref: a7fc56f262863f374b44aa020e163c013d3c75ad
+          head-ref: 20063fbd0a3dde28a87d0a8767a4f16c7a5c9c6e
 
       - name: Check changed files output
         run: |
           changed_files="${{ steps.changed-files.outputs.changed-files }}"
+          # We know that `renovate.json` is not changed between the two refs
           expected_file="renovate.json"
 
           if echo $changed_files | grep -F -q -x "$expected_file"; then
@@ -56,30 +88,3 @@ jobs:
             echo "$expected_file not found in changed files"
           fi
 
-  test-known-refs:
-    name: Check that changed-files action works with custom refs
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 1
-
-      - name: Get changed files
-        id: changed-files
-        uses: ./changed-files
-        with:
-          base-ref: a7fc56f262863f374b44aa020e163c013d3c75ad
-          head-ref: 20063fbd0a3dde28a87d0a8767a4f16c7a5c9c6e
-
-      - name: Check changed files output
-        run: |
-          changed_files="${{ steps.changed-files.outputs.changed-files }}"
-          expected_file="changed-files/action.yml"
-
-          if [[ $changed_files =~ $expected_file ]]; then
-            echo "$expected_file found in changed files"
-          else
-            echo "$expected_file not found in changed files"
-            exit 1
-          fi
